---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04

suites:
  - name: deploy
    run_list:
      - recipe[homepage::setup]
      - recipe[homepage::nginx]
      - recipe[homepage::app]
      - recipe[homepage::deploy]
    attributes:
